# Dependencies
markdown:         kramdown
rouge:            true

# Permalinks
permalink:        pretty

# Setup
title:            Wade R. Roberts
tagline:          'Evolutionary Genomics'
description:      'Botanist and Ph.D. Candidate'
institution:      'Washington State University'
url:              http://achimen.es
copyright-year:   2018

theme-cfg:
  avatar:         /images/avatar.jpg
  background:     /images/bg.jpg

author:
  name:           'Wade R. Roberts'
  twitter:        https://twitter.com/wwaaaddddeee
# facebook:       https://twitter.com/wwaaaddddeee
# instagram:      https://twitter.com/wwaaaddddeee
  github:         https://github.com/wrroberts
  scholar:        https://scholar.google.com/citations?user=FRciU2oAAAAJ
# dribbble:       https://twitter.com/wwaaaddddeee
  email:          wade@achimen.es
# email:          dr.roberts@achimen.es
  mailing:        'French Ad 324<br /> PO Box 641030<br /> Pullman, WA  99164-1030<br /> United States'
  phone:          '1-509-335-1716'

# paginate:         5

github:
  repo:           https://github.com/wrroberts/wrroberts.github.io
